services:
  - type: web
    name: speech-ai
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y ffmpeg && 
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.11.6
